Task/upgrade crc and LUK
openlattice/care pull request #840
Opened 2021-02-24 21:42 UTC by giuliacampana

2021-02-24 21:43 UTC, UnsungHero97 requested changes

2021-02-24 21:43 UTC, UnsungHero97 commented on package.json
> +    "lattice-ui-kit": "~0.42.0",
Please confirm this isn't going to break anything.

2021-02-24 23:06 UTC, UnsungHero97 approved these changes

2021-02-25 00:36 UTC, solomontang approved these changes

2021-02-25 00:36 UTC, merged